<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>bg.hristomanov.education</groupId>
    <artifactId>education</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>pom</packaging>

    <name>education</name>
    <description>Executable Java and Spring engineering knowledge base</description>

    <modules>
        <module>java/concurrency/project-loom</module>
        <module>java/jvm/jfr-troubleshooting</module>
    </modules>
</project>
