spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/education
    username: education
    password: education
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  data:
    redis:
      host: localhost
      port: 6379
